### ISSUE TITLE
web version not working

### ISSUE THREAD

**Issue by js08** [MoOx/react-native-boilerplate#2]
Hi,

I downloaded the project from the below URL, and did npm install but still in browser I am seeing the app.
But I am seeing the ios and android app, can you tell me how to work it in web. attaching screenshot too.

For web I hit 3000 and 8001 port but still not working.

https://github.com/MoOx/react-native-boilerplate

<img width="1440" alt="Screen Shot 2020-07-17 at 3 42 41 PM" src="https://user-images.githubusercontent.com/1699943/87829392-9c125580-c844-11ea-887a-d8345ca7a953.png">

**Comment by MoOx** [comment]
Did you run `yarn start:web` and used the url of the server that will be displayed in your terminal?

**Comment by js08** [comment]
@MoOx Hey if I run npm start it runs, and if I point to this URL http://localhost:8081/ I see some output but it doesn't match output in ios and android simulator, can you tell me why
Attaching screenshots
<img width="1440" alt="Screen Shot 2020-07-17 at 7 56 29 PM" src="https://user-images.githubusercontent.com/1699943/87840954-d3dec480-c867-11ea-8ff4-845e051f2789.png">

**Comment by MoOx** [comment]
It's `start:web` for the web, not just `start`
