### ISSUE TITLE
boiler plate command not working

### ISSUE THREAD

**Issue by js08** [MoOx/react-native-boilerplate#3]
when I try to execute the below command I am getting the below error, even in package.json I don't see react native web, can you tell me how to fix it.

npx react-native init ProjectName --template react-native-boilerplate

command error
https://gist.github.com/js08/7fd20ab83f8ea985e515e6e59d14772f

package.json
https://gist.github.com/js08/bd3a2ed7b695246acae6546d47f3dbe3

**Comment by MoOx** [comment]
This command is incorrect, sorry. Try with 

```
npx react-native init ProjectName --template https://github.com/MoOx/react-native-boilerplate
```
